name: deploy-auth

on: 
  push: 
    branches:
      - master
    paths:
      - 'auth/**'

jobs:
  build:
  
#     We can run commands in here as we are running an ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t kesuion/auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
#       This registers our docker secrets
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
          
      - run: docker push kesuion/auth
      
      
      
